model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 1
    n_embed: 8192
    image_key: "depth"
    ddconfig:
      double_z: False
      z_channels: 1
      resolution: 512
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,1,2,2,4,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    # lossconfig:
      # target: torch.nn.Identity

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 8
    train:
      target: taming.data.custom.CustomDepthTrain
      params:
        training_images_list_file: /data/ssd2/abhiroop/LDM-SRtuning/src/taming-transformers/train.txt
        size: 256
        max_depth: 1218.31
    validation:
      target: taming.data.custom.CustomDepthTest
      params:
        test_images_list_file: /data/ssd2/abhiroop/LDM-SRtuning/src/taming-transformers/val.txt
        size: 256
        max_depth: 1218.31

